### ISSUE TITLE
QueryBuilder in xpc-sys?

### ISSUE THREAD

**Issue by kaisq** [mach-kernel/launchk#15]
I ran across the `xps-sys` library, which looks like it's exactly what I need for a project that talks to `launchd`. However, the `xpc-sys` library references a `QueryBuilder` trait, which doesn't seem to exist within the `xpc-sys` crate, but instead in the `launchk` crate. Should the `QueryBuilder` trait get moved into the `xpc-sys` crate so that it's available for use to `xpc-sys` consumers?

**Comment by mach-kernel** [comment]
@kaisq whoops -- yes that's quite inconvenient 😅! Will fix that and post a new release. Hang tight!

**Comment by kaisq** [comment]
Thanks for the quick response! I see the PR you opened and it looks pretty straightforward and the build passed -- is that close to release?

**Comment by mach-kernel** [comment]
Yes, pardon the delay. Very busy week for me. I'll stamp a release tonight.

**Comment by mach-kernel** [comment]
Here you go, @kaisq! -- https://crates.io/crates/xpc-sys/0.4.0

Please keep in touch: my use case is tiny for the TUI, it doesn't make very many XPC queries. If something is broken I welcome any contributions (test cases, bug reports, PRs, or otherwise)!

Thanks so much for reaching out! 😄
