### ISSUE TITLE
xpc-sys fails to build

### ISSUE THREAD

**Issue by n8henrie** [mach-kernel/launchk#19]
I'm on an M1 mac, not sure if that matters, I made the change in https://github.com/mach-kernel/launchk/issues/4 without success.

```console
$ rustc --version
rustc 1.71.0 (8ede3aae2 2023-07-12)c
$ cargo build
   Compiling xpc-sys v0.4.0 (/Users/n8henrie/git/launchk/xpc-sys)
warning: unused doc comment
  --> xpc-sys/src/lib.rs:26:1
   |
26 | / /// Some extra private API definitions. Thanks:
27 | | ///
28 | | /// https://developer.apple.com/documentation/kernel/mach
29 | | /// https://chromium.googlesource.com/chromium/src.git/+/47.0.2507.2/sandbox/mac/xpc_private_stubs.sig
   | |______________________________________________________________________________________________________^
30 | / extern "C" {
31 | |     // Can decode i64 returned in "errors" for XPC responses
32 | |     pub fn xpc_strerror(err: c_int) -> *const c_char;
33 | |     pub static errno: c_int;
...  |
60 | |     pub static _os_alloc_once_table: [_os_alloc_once_s; 10];
61 | | }
   | |_- rustdoc does not generate documentation for extern blocks
   |
   = help: use `//` for a plain comment
   = note: `#[warn(unused_doc_comments)]` on by default

error[E0507]: cannot move out of `self.content` which is behind a shared reference
     --> /Users/n8henrie/git/launchk/target/debug/build/xpc-sys-6218adb712f8e8d0/out/bindings.rs:19279:5
      |
19273 | #[derive(Debug)]
      |          ----- in this derive macro expansion
...
19279 |     pub content: __IncompleteArrayField<u8>,
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `self.content` has type `__IncompleteArrayField<u8>`, which does not implement the `Copy` trait
      |
      = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0507`.
warning: `xpc-sys` (lib) generated 1 warning
error: could not compile `xpc-sys` (lib) due to previous error; 1 warning emitted
```

**Comment by mach-kernel** [comment]
Thanks! Let me know if `master` builds correctly for you now 😸

**Comment by timsutton** [comment]
I was running into this issue as well. This may be naïve but could this be as simple as removing the definition of `xpc_dictionary_set_mach_send`, like [this](https://github.com/timsutton/launchk/commit/bc4cc73649b855a7a0267818fdbd87982deb8416)?

**Comment by mach-kernel** [comment]
I'm having issues reproducing on my machine. Running Sonoma 14.1.1. What macOS version are ya'll running?

```bash
Darwin dstancu-mbp 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64
```

**Comment by timsutton** [comment]
@mach-kernel Thanks for responding!

My system is Sonoma 14.4.1 / Xcode 15.3 and I noticed it's defined at `Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/xpc/xpc.h`, but I don't see that defined in _any_ Xcode MacOSX platform from previous Xcode / SDK versions.

According to https://xcodereleases.com/, Xcode versions prior to 15.3 included the Ventura (macOS 13.5+) SDK and not Sonoma (macOS 14.0).

So I think this explains the recency and at what point the new definition appeared in the XPC headers.

**Comment by mach-kernel** [comment]
Aha -- that makes sense. I think we can fix this by using the [`xcrun`](https://docs.rs/xcrun/latest/xcrun/) crate to see what SDK versions we have available, then customize the bindgen behavior accordingly. Maybe also add some smoke tests with GHA macOS runners.

I can PR this sometime during the week or if you want, you can take a stab at it.

```
xcodebuild -version
Xcode 14.3.1
Build version 14E300c
```

Thanks much for chasing this down 😄

**Comment by timsutton** [comment]
@mach-kernel Thanks for the nudge :)

I made an initial pass at the smoke test idea in a PR to my own fork [here](https://github.com/timsutton/launchk/pull/1/files). I didn't get to the point of customizing the bindgen builder behaviour in a way conditional based on the SDK version detected, but I was happy to see that with filtering it always in `blocklist_function` that it's green either way.

Would you still prefer an approach where `blocklist_function` is done conditionally (or at least, add a comment to your fn definition that this would be getting filtered out on newer SDKs)? I'm happy to clean this branch up and open a proper PR as a starting point if you'd be able to give some guidance on any changes to the bindgen usage. I'm a total Rust noob.

I could also see it being a good jumping off point in being able to define some other smoke tests of example usages, in order to exercise the built code.

**Comment by mach-kernel** [comment]
I looked at your branch and I'm happy with always doing blocklist for that declaration (I expected there to be more differences). Awesome: PR it (and, thank you!)

Re tests, there are some for going back/forth between XPC/Rust data structures -- feel free to add more as you see fit. A good starting place would be the `XPCPipeable` trait. I'm not so sure my naive scheme of checking for potential error keys in XPC replies covers all the bases.

https://github.com/mach-kernel/launchk/blob/master/xpc-sys/src/objects/xpc_dictionary.rs#L192
https://github.com/mach-kernel/launchk/blob/master/xpc-sys/src/traits/xpc_value.rs#L123

**Comment by timsutton** [comment]
PR up in https://github.com/mach-kernel/launchk/pull/23. Thanks!
