### ISSUE TITLE
XPCObject::default() crashes on drop

### ISSUE THREAD

**Issue by hjmallon** [mach-kernel/launchk#21]
`let a = XPCObject::default();`

Add that to a test and I get `(signal: 11, SIGSEGV: invalid memory reference)`. `xpc_release` cannot be called on nullptr.

**Comment by mach-kernel** [comment]
I opened #22, but I would love your thoughts on potentially dropping `Default`. If you don't go to XPCObject from a Rust type, you can always use `From<xpc_object_t>. So I don't think there's any clear default value to yield.
